#
#			2017
# 	Modified by AP0904225 <ap0904225@qq.com>  on the basis of odroid board
#
# Configuration settings for the FriendlyARM TINY4412 (EXYNOS4412) board.
#     FriendlyARM Tiny4412 SDK board hardware version:
#           core board   :  Tiny4412-1412
#          bottom board :  Tiny4412/Super4412SDK 1506
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	:= tiny4412.o
